dadj1 = input("Describing Adjective 1: ")
color1 = input("Color 1: ")
color2 = input("Color 2: ")
pthing = input("1 Plural Thing: ")
dadj2 = input("Describing Adjective 2: ")
name = input("Name: ")
gender = input("Pick He/She: ")
number = input("Number: ")
noun1 = input("Noun 1: ")
noun2 = input("Noun 2: ")
noun3 = input("Noun 3: ")
pverb = input("Plural Verb: ")
cloth = input("Clothing: ")
dadj3 = input("Describing Adjective 3: ")

print("It’s almost Christmas and look! It’s a " + dadj1 + " day today. With the " + color1 + " sky and the " + color2 + " " + pthing + " on the ground, this day is going to be absolutely, " + dadj2 + " day. You go outside and you look upon the roof. Why its " + name + "! What is " + gender + " doing on your roof? " + gender + " says that " + gender + " has been waiting up there for " + number + " days just trying to find a way to get down. So you go into the garage but you couldn’t decide what to help the person down. Do you help the person down with, the " + noun1 + ", the " + noun2 + ", or the " + noun3 + "? So you just grab all 3 and use them all to help " + name + ". They thank you and " + gender + " " + pverb + " off with your " + cloth + ". Well this was a " + dadj3 + " day.")
