import turtle as trtl

bob = trtl.Turtle()

r = input("What radius do you want to use for your circle? ")
r = int(r)
outC = input("What Color do you want for your outline? ")
fillC = input("What color do you want to fill your circle with? ")

bob.penup()
bob.goto(-150,-150)
bob.pendown()
bob.color("green")
bob.begin_fill()
bob.goto(-100,50)
bob.goto(-50,-150)
bob.goto(-150,-150)
bob.end_fill()
bob.penup()
bob.goto(-100,-100)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-120,-120)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-80,-120)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-100,-120)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-120,-100)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-80,-100)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-110,-80)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-90,-80)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-110,-60)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-90,-60)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-100,-40)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-100,-20)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-110,-140)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-90,-140)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-130,-140)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-70,-140)
bob.pendown
bob.color(outC, fillC)
bob.begin_fill()
bob.circle(r)
bob.end_fill()
bob.penup()
bob.goto(-120,40)
bob.pendown
bob.color("yellow")
bob.begin_fill()
bob.goto(-100,80)
bob.goto(-80,40)
bob.goto(-120,60)
bob.goto(-80,60)
bob.goto(-120,40)
bob.end_fill()
bob.penup()
bob.goto(-120,-150)
bob.color('#382E00')
bob.pendown()
bob.begin_fill()
bob.goto(-120,-180)
bob.goto(-80,-180)
bob.goto(-80,-150)
bob.end_fill()

window = trtl.Screen()
window.mainloop()